apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  # Job이 최대 몇 초 걸릴 것이냐. 3초 넘어서면 실패가 되는 스크립트임.
  activeDeadlineSeconds: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: ubuntu:focal
        command: ["sh", "-c", "sleep 5; echo Hello, World!"]