apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  ### replicaset의 옵션 ###
  replicas: 3
  selector:
    matchLabels:
      app: hello
  ########################

  ### Replicaset 이 만드는 Pod 템플릿 ###
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:plain-text
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
