version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_container
    environment:
      - "TZ=Asia/Seoul"
    ports:
      - "8080:8080"
    volumes:
      - "./data:/var/jenkins_home"