apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: hello
spec:
  limits:
  - type: Container
    default:
      memory: 128mi
      cpu: 100m
    defaultRequest:
      memory: 64mi
      cpu: 50m
    max:
      memory: iGi
      cpu: 1000m
    min:
      memory: 16Mi
      cpu: 10m
  - type: Pod
  - type: PersistentVolumeClaim
    min: 
      storage: 100Mi
    max: 
      storage: 1Gi