FROM openjdk:11

VOLUME /tmp

ADD build.gradle.kts ./
RUN gradle build -x test --parallel --continue > /dev/null 2>&1 || true


ARG JAR_FILE=build/libs/application-1.0.jar
ADD ${JAR_FILE} ./application-1.0.jar


RUN java -Djarmode=layertools -jarFROM python:3.10.5

ENV BUILDKIT_PROGRESS=plain

# Copy Source Codes
COPY . /daliyInGsm
WORKDIR /daliyInGsm

# Install Python Packages
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Copy Entrypoint Script
COPY docker-entrypoint.production.sh /docker-entrypoint.production.sh
RUN chmod +x /docker-entrypoint.production.sh application-1.0.jar extract

COPY build/libs/dependencies/ ./
RUN true

COPY build/libs/spring-boot-loader ./
RUN true

COPY build/libs/snapshot-dependencies ./
RUN true

COPY build/libs/application ./
RUN true

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/application-1.0.jar","--spring.profiles.active=prod","--redis.host=10.0.28.60"]