FROM openjdk:11

VOLUME /tmp

ADD build.gradle.kts ./
RUN gradle build -x test --parallel --continue > /dev/null 2>&1 || true


ARG JAR_FILE=build/libs/application-1.0.jar
ADD ${JAR_FILE} ./application-1.0.jar


RUN java -Djarmode=layertools -jar application-1.0.jar extract

COPY build/libs/dependencies/ ./
RUN true

COPY build/libs/spring-boot-loader ./
RUN true

COPY build/libs/snapshot-dependencies ./
RUN true

COPY build/libs/application ./
RUN true

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/application-1.0.jar","--spring.profiles.active=prod","--redis.host=10.0.28.60"]